import type { NextPage } from "next";
import Head from "next/head";
import Nav from "../../components/Nav";
import s from "../../../styles/Film.module.css";

import Wrapper from "../../components/Wrapper";
import Heading from "../../components/Heading";
import AddWatchlist from "../../components/AddWatchlist";
import InfoText from "../../components/InfoText";

const FilmPage: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link
          href="http://fonts.googleapis.com/css?family=Signika"
          rel="stylesheet"
          type="text/css"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper>
        <Wrapper.Header headerStyles={s.header}>
          <Nav names={["Home", "Watchlist"]} links={["/", "/"]} />
        </Wrapper.Header>
        <Wrapper.Main classNames={s.main}>
          <div className={s.filmContainer}>
            <div className={s.posterContainer}>
              <img className={s.poster} src={"/CardPic.svg"} />
              <div className={s.name}>
                <Heading level={1}>Avatar</Heading>
                <AddWatchlist chosen={false} classNames={s.watchlist} />
              </div>
              <div className={s.rating}>
                <img src="/Rating.svg" className={s.star} />
                <span className={s.mark}>8.9</span>
              </div>
            </div>
            <div>
              <div className={s.info}>
                <div className={s.infoContent}>
                  <InfoText content="Timur" name="Timur" />
                  <InfoText content="Timur" name="Timur" />
                  <InfoText content="Timur" name="Timur" />
                  <InfoText content="Timur" name="Timur" />
                </div>
              </div>
              <div></div>
              <div></div>
            </div>
          </div>
        </Wrapper.Main>
      </Wrapper>
    </div>
  );
};

export default FilmPage;
