import type { NextPage } from "next";
import Head from "next/head";
import Card from "../components/Card";
import CardContainer from "../components/CardContainer";
import SearchField from "../components/SearchField";
import Wrapper from "../components/Wrapper";

const Home: NextPage = () => {
  const handleSearchSubmit = (value: string) => {
    alert(value);
  };
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link
          href="http://fonts.googleapis.com/css?family=Signika"
          rel="stylesheet"
          type="text/css"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper>
        <Wrapper.Header>
          <SearchField handleSubmit={handleSearchSubmit} />
          <img src="/AddWatchlist.svg" height="26px" />
        </Wrapper.Header>
        <Wrapper.Main>
          <CardContainer>
            <Card />
            <Card />
            <Card />
            <Card />
            <Card />
            <Card />
          </CardContainer>
        </Wrapper.Main>
      </Wrapper>
    </div>
  );
};

export default Home;
