import type { NextPage } from "next";
import Head from "next/head";
import dynamic from "next/dynamic";
import Image from "next/image";
import App from "../components/App";

const DynamicHeader = dynamic(() => import("../components/App"), {
  ssr: false,
});

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link
          href="http://fonts.googleapis.com/css?family=Signika"
          rel="stylesheet"
          type="text/css"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <App />
    </div>
  );
};

export default Home;
